- .storybook/config.ts
- .storybook/custom-story.css
- src/components/Tag/Tag.stories.tsx
- src/components/Tag/Tag.test.tsx
- src/components/Tag/Tag.tsx
I wanted to use the `Tag` component but with a custom `className`. This PR updates the `Tag` component to take an optional `className` prop and append it to the default class of `usa-tag`.
Updated tests and storybook for this as well.
> Support custom classNames for Tag

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.test.tsx
- src/components/Button/Button.tsx
During our use we found that `small` and `icon` classes were not available.
> Add small and icon options to Button

- package.json
- yarn.lock
This doesn't fix the `kind-of` issue but does fix the other two alerts attached to this repo. Kind of is a lot messier so I think we can hold out a few more days to see if big maintainers like storybook and FB will fix their deps. It cleans up yarn audit output *a ton*.
security advisory: [Prototype pollution in minimist](https://github.com/advisories/GHSA-vh95-rmgr-6w4m)
came from gonzales-pe pkg via postcss-sass
- fixed in tonyganch/gonzales-pe#304 (=> `4.3.0`)
- incorporated in AleshaOleg/postcss-sass#143 (=> `0.4.4`)
I could have fixed by patching yarn.lock alone, but used the force upgrade method for explictness here. See my work in b8e6805d, c0f0a829, and 791b1e27.
security advisory: [Regular Expression Denial of Service in Acorn](https://github.com/advisories/GHSA-6chw-6frg-f759) …
> resolve 2/3 security advisories

- yarn.lock
Trying to streamline getting the dependabot changes in without having to deal with `yarn.lock` conflicts manually.
There is one outstanding audit issue, but @storybook/addon-info doesn't have an upgrade available yet.
> combine upgrades from PRS 60-70

- .circleci/config.yml
**Fixes #103** 
Fix spurious CI failures due to not enough memory while running Jest tests, by limiting Jest to a single thread.
References:
- https://discuss.circleci.com/t/not-enough-memory-while-testing-a-node-js-appplication/12768
- https://blog.lysender.com/2019/08/jest-tests-failing-on-circleci-enomem-not-enough-memory/
> Limit Jest to 1 worker when running in CI

- src/components/Alert/Alert.stories.tsx
- src/components/Alert/Alert.test.tsx
- src/components/Alert/Alert.tsx
**Fixes #106** 
Adds support for new Alert styles (slim, no icon) as well as React HTML attributes such as `className`.
> Add new styles to Alert, add HTML props

- src/components/Title/Title.stories.tsx
- src/components/Title/Title.test.tsx
- src/components/Title/Title.tsx
This PR adds the Title component. This component may be used through out an application, and is included in the USWDS Header Component: https://designsystem.digital.gov/components/header/
Should this component be composed in an alternate manner to make it more reuse-able?  
To test this component execute the following commands in the react-uswds repo:
```
yarn install
yarn storybook
```
Navigate to the Title component.
> Add title component

- src/components/Footer/Address/Address.stories.tsx
- src/components/Footer/Footer.stories.tsx
- src/components/Footer/FooterNav/FooterNav.stories.tsx
- src/components/Footer/FooterNav/FooterNav.test.tsx
- src/components/Footer/FooterNav/FooterNav.tsx
- src/components/Footer/Logo/Logo.stories.tsx
- src/components/Footer/SignUpForm/SignUpForm.stories.tsx
- src/components/Footer/SignUpForm/SignUpForm.test.tsx
- src/components/Footer/SignUpForm/SignUpForm.tsx
- src/components/Footer/SocialLinks/SocialLinks.stories.tsx
- src/components/forms/TextInput/TextInput.tsx
-  Add `ExtendedNav` behavior to `FooterNav`
-   Add `SignupForm`
PR (3 of 3) for #78
> Add big footer

- CHANGELOG.md
- dangerfile.ts
- package.json
- src/components/grid/Grid.stories.tsx
- src/components/grid/Grid/Grid.test.tsx
- src/components/grid/Grid/Grid.tsx
- src/components/grid/GridContainer/GridContainer.test.tsx
- src/components/grid/GridContainer/GridContainer.tsx
- src/components/grid/types.ts
- src/index.ts
This PR adds some components to help render content within the [USWDS grid layout](https://designsystem.digital.gov/utilities/layout-grid/), along with Storybook stories to demonstrate how they can be used.
**GridContainer** -- Renders children inside a `<div>` and implements a grid container size which can be also specified via props.
**Grid** -- Renders children inside a `<div>` and accepts props to help determine how the div should layout within the grid container. A set of these props (`GridItemProps = row, col, gap, offset`) can be passed in directly to the `Grid` component, and/or they can also be passed in as an object to a breakpoint size prop to assign those classes to be applied at that breakpoint and above. See examples below.
```
// Two cells spanning 3 and 9 columns within …
```
> feat: add Grid components #86

- package.json
- yarn.lock
```con
yarn audit v1.22.4
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ yargs-parser                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @storybook/storybook-deployer                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ …
```
> chore: upgrade sb-deployer (patch upgrade 2.8.5 => 2.8.6)

- src/components/forms/Form/Form.tsx
The `usa-search` class was being added twice when using the Search component because it was also being defined on the Form component.
This leaves the class on the Search component in favor of removing it from the Form component.
fix #163
> fix: removes the usa-search class name from the form component

- src/components/Search/Search.stories.tsx
- src/components/Search/Search.tsx
- yarn.lock
The Search component previously hardcoded the id and name attributes to 'search-field' and 'search', of the rendered input and label elements.
This adds `id` and `name` as props to the Search component allowing overriding of the default values.
Also updates the storybook documentation USWDS link to be correct.
Fixes #162
> fix: accept id and name props for Search component input field

- src/components/header/Header/Header.stories.tsx
- src/components/header/MegaMenu/MegaMenu.tsx
- src/components/header/Menu/Menu.tsx
The NavDropDownButton has a `menuId` property configured but the Menu and MegaMenu components were not passing unordered list attributes to through to their NavList components so the id was not connected.
A header menu story had two NavDropDownButton components with the same `menuId` so I updated those to be unique.  If there are other tests or stories that make sense to add/update let me know.
fix #165
> fix: extends header menu to accept list props for corresponding id

- src/components/GovBanner/GovBanner.stories.tsx
- src/components/GovBanner/GovBanner.test.tsx
- src/components/GovBanner/GovBanner.tsx
This was only a minor change of a div element to a section element. Additionally, I added props to the section element so html attributes like an aria-label could be passed into the component. 
Please let me know if adding the html attributes is over kill. I mainly added them so an aria label could be passed through. When I was comparing the guidance markup and our component markup the lack of the label was the only difference I saw after updating the div to a section.
> fix: update gov banner to new version

- README.md
- docs/for_trussels.md
Adds some documentation specifically for Trussels who are looking to get more or less involved in this project! I also took the opportunity to update the README following the best practices outlined at https://github.com/RichardLitt/standard-readme
Fixes #185
Fixes #97
> docs: add documentation for Trussels

- package.json
- src/components/forms/RangeInput/RangeInput.stories.tsx
- src/components/forms/RangeInput/RangeInput.test.tsx
- src/components/forms/RangeInput/RangeInput.tsx
- src/index.ts
This PR adds the [USWDS Range](https://designsystem.digital.gov/components/form-controls/#range) component to the available form inputs.
The component renders as an input of type range and an optional Label.
The min, max, step, and value fields are optional and default to:
**min**: 0
**max**: 100
**step**: 1
**value**: max/2
I copied the ref code from somewhere else but don't know entirely why it's necessary or all of the possible types it could be.  I think I remember there is an old deprecated way to do refs from the official tutorial.
- Should the label be excluded all together from the component or passed whole instead of built out of label and hint attributes?
- The USWDS guidance recommends that you label the min and max ends, should we offer that functionality?
- Should the …
> feat(rangeinput): creates form RangeInput component, test, and stories

- .github/pull_request_template.md
Adding a new pull request template as per  #73 
We will be able to test this once it is merged.  
Question: Would you find the comments in the template helpful or annoying to work around?
> docs: Add new pull request template #73 

- CODEOWNERS
- docs/adding_new_components.md
- docs/contributing.md
- New docs live in new file - `adding_new_components.md`.  Other titles welcome.  Sections include Checklist, Navigating Documentation, Guiding Patterns, and Common Components 
- Reorganized "Development" docs slightly (added Pull Requests section to highlight that info).
- Add table of contents to `contributing.md`
closes #73 
- Feel free to make commits or suggestions directly with edits.
> docs: adding new components docs, rework development docs #73

- .dependabot/config.yml
We recently renamed labels in our repo, should update dependabot config to reflect this.  
#260 - example of dependabot PR warning that outdated default labels don't exist
n/a - next round of dependabot PRs shouldn't have the warning
> ci: Adjust default labels for dependabot

- src/components/Footer/Logo/Logo.stories.tsx
- src/components/Footer/Logo/Logo.test.tsx
- src/components/Footer/Logo/Logo.tsx
Use a `size` enum prop, deprecate `big` and `medium` boolean props
* fixes #264
> feat(Logo): use size prop, deprecate boolean types

- src/components/Footer/Address/Address.stories.tsx
- src/components/Footer/Address/Address.test.tsx
- src/components/Footer/Address/Address.tsx
Use `size` enum prop, deprecate boolean `big`, `medium`, and `slim` props
* closes #265
> feat(Address): convert to enum size prop, deprecate boolean

- src/components/Search/Search.stories.tsx
- src/components/Search/Search.test.tsx
- src/components/Search/Search.tsx
Convert to use `size` enum prop, deprecate `big` and `small` boolean props
closes #266
> feat(Search): add size enum prop, deprecate big,small boolean props

- package.json
Adjust `standard-version` config.
- `-t` is not a boolean flag- needs the empty string to understand git tags correctly
- auto committing the changelog and version bump will make our commits more standardized and speed up releases.  We can continue to manually add tags in GH for now since we are also still adjusting our git flow
#287 
- Pull down branch, rebase against master and run `yarn release --dry-run`. Only the latest changes should show up in changelog. This change along with moving to a single branching flow (#216) should resolve our changelog issues.
> fix(standard-version): use -t flag correctly, autocommit 

- src/components/header/MegaMenu/MegaMenu.tsx
- src/components/header/Menu/Menu.tsx
Quick cleanup before next release (1.7.0).
cleanup from #267 
- `yarn test -w` has no warnings
> fix: refactor menu, megamenu to use current props;  removes deprecation warnings from tests

- README.md
- docs/contributing.md
- example/package.json
- example/yarn.lock
- package.json
- yarn.lock
-  Remove `commitizen` dependencies since we no longer lint on commits, only on PR titles (which uses a GH workflow).
- Upgrade example app dependencies; this takes `yarn audit` vulnerabilities down from 4000+ to 1. Also removes a variety of lodash warnings.
https://github.com/trussworks/react-uswds/network/alert/example/yarn.lock/lodash/open
> fix: remove commitizen, upgrade example app dependencies

- dangerfile.ts
- docs/contributing.md
- package.json
Update danger config to run `yarn audit` and block if high or critical issues are found.
Do not run danger on dependabot PRs
Do not warn if the only changes the `package.json` is the version
closes #324
> feat(danger): Block PR if yarn audit has high or critical, do not run on dependabot, no warn on version

- yarn.lock
Upgrade danger to version where `danger local` works with non `master` default branch
> chore(danger): Upgrade danger to fix `danger local` on main

- docs/contributing.md
Add more docs about conventional commits
> docs: Even more info and emphasis on conventional commits

- .storybook/main.js
- .storybook/preview.js
- package.json
- yarn.lock
This PR was originally #375 but was reopened from a CODEOWNER so the CI checks can run.
This change adds the [Viewport](https://github.com/storybookjs/storybook/tree/master/addons/viewport) addon and sets up storybook to allow users to test their stories using alternate viewport sizes.  I added a global configuration so that all stories have access to the same default set of viewports, but additional customization per-story is possible if required.
Implements https://github.com/trussworks/react-uswds/issues/253
In the toolbar above the canvas area, a new icon exists.  Clicking this icon will open a dropdown menu with a number of viewport options.  Selecting a viewport should will the story canvas size, and also allow you to change the orientation of the simulated view.
> docs: add addon-viewports using the included INITIAL_VIEWPORTS list

- dangerfile.ts
Fix spurious warnings on changes to example code
fixes #373
See reproduction instructions in #373
> ci(danger): fix spurious warnings on changes to example code

- README.md
- example/package.json
- example/src/App.tsx
- example/src/pages/Icons.tsx
- example/yarn.lock
- yarn.lock
This PR adds documentation to the README that recommends the use of `react-fontawesome` for projects that need icons.
I'm not sure if/what should be added to the example app. I put a page in there to make sure that the icons worked, but I can take that out if it doesn't make sense to keep since it is testing an external dependency.
closes #84 
* Read through the *Icons* section of the docs for clarity.
* Open the example app locally and look at the *Icons* page.
Here is the new page in the example app:
> docs: Point users to react-fontawesome for icons

- webpack.config.js
Update webpack config to [support umd build for both browsers and node](https://webpack.js.org/configuration/output/#outputglobalobject)
closes #380
Create the file `ssr.js` in the root of the `react-uswds` project
```js
const react = require('react')
const domServer = require('react-dom/server')
const uswds = require('./lib')
const TagFactory = react.createFactory(uswds.Tag)
const app = domServer.renderToString(TagFactory())
console.log(app)
```
1. `yarn build`
1. `NODE_ENV=production node ssr.js`
> build(webpack): support browsers and node 

- CHANGELOG.md
- package.json
- yarn.lock
* **ButtonGroup:** Add new component ButtonGroup ([#382](https://github.com/trussworks/react-uswds/issues/382)) ([a7b84d6](https://github.com/trussworks/react-uswds/commit/a7b84d6ebd9a144412faf9685d80310204566ba8))
* **CharacterCount:** Add new component CharacterCount ([#383](https://github.com/trussworks/react-uswds/issues/383)) ([cc12034](https://github.com/trussworks/react-uswds/commit/cc120342c3a6484227b6bab00d18c4ce8212d30c))
* add addon-viewports using the included INITIAL_VIEWPORTS list as default for all stories ([#376](https://github.com/trussworks/react-uswds/issues/376)) ([9683b40](https://github.com/trussworks/react-uswds/commit/9683b400769e63bb3035c986acc253ffdc2f008b))
* **Validation:** Add new Validation components …
> chore(release): 1.9.0

- .github/dependabot.yml
Adjust config to merge earlier in day to avoid conflicts during releases.  Also, ignore react dependencies in `/example` (like we already do in the root level config). 
Related to #325
> ci(dependabot): Adjust config to merge earlier in day, ignore react dependencies

- package.json
- yarn.lock
Uses the `resolutions` key in `package.json` to resolve the `bl` dependency to `^4.0.3` in order to fix a high severity vulnerability.
none
`yarn audit` on the main branch:
```
10:50:28 in truss-uswds-react on  main is 📦 v1.9.1 suz⬢ 12.16.2 
➜ yarn audit
yarn audit v1.22.4
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Remote Memory Exposure                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ bl                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.2.3 <2.0.0 || >=2.2.1 <3.0.0 || >=3.0.1 <4.0.0 ||        │
│               │ >=4.0.3 …
```
> chore: Update bl dependency to resolve security advisory

- .circleci/config.yml
- .github/dependabot.yml
Try again- this time only run Happo if the `CIRCLE_USERNAME` exists (is not empty).  Also add storybook to dependencies we ignore for dependabot and manually update.
closes #450 
Have to merge to test
> fix:  Happo automation should skip dependabot PRs

- .circleci/config.yml
Only run happo if GITHUB_USERNAME is set to fix dependabot
fixes #450
Watch dependabot PRs after merge
> fix: Only run happo if GITHUB_USERNAME is set to fix dependabot

- .circleci/config.yml
Dependabot PRs are blocked up again due to Happo. I saw discussion of slack that we want try, instead, running happo for every PR again. In that case, removing conditional logic in circleci config about this.
Related to #450 
Can be tested on merge.
> ci: Run Happo for every PR again

- package.json
- yarn.lock
- adjust typescript minimum version and fix `yarn build`
resolves #520 
- clearing out `node_modules`, `yarn` and then `yarn build` should all run without bugs. 
- Tests and Happo should pass.
> fix: Require Typescript 3.8+

- example/package.json
- example/yarn.lock
Fixes security warning in GitHub from example app
> build(deps-dev): Bump react-scripts in example to 3.4.4

- .circleci/config.yml
Update config to add auth. 
closes #633 
- CI should run successfully
> ci: Add docker auth to circleci config

- .circleci/config.yml
Use the [CircleCI Approved pattern for caching yarn](https://circleci.com/docs/2.0/yarn/#caching) (and not node_modules)
closes #731 
If CircleCI passes, we're good
> ci: Use yarn cache in CircleCI

- src/components/Footer/Address/Address.test.tsx
- src/components/Footer/Address/Address.tsx
- src/components/Footer/SocialLinks/SocialLinks.test.tsx
- src/components/Footer/SocialLinks/SocialLinks.tsx
- src/components/header/MegaMenu/MegaMenu.test.tsx
- src/components/header/MegaMenu/MegaMenu.tsx
- src/components/header/Menu/Menu.test.tsx
- src/components/header/Menu/Menu.tsx
- src/components/header/NavCloseButton/NavCloseButton.test.tsx
- src/components/header/NavCloseButton/NavCloseButton.tsx
Add `className` prop and tests for custom classes on small subcomponents.
resolves #488
Happo should pass
> fix: Add className handling to header and footer subcomponents

- .github/dependabot.yml
Make updates to the library and the `/example` app node dependencies at the same time. By using the [default](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#scheduletime) updates will happen before work starts on Mondays.
> ci: Make dependabot updates at the same time

- LICENSE
- README.md
- docs/contributing.md
- docs/faqs.md
- docs/for_trussels.md
It's a new year. Also there were a bunch of broken links 🤕 from an earlier refactor.
> docs: Update license to 2021

- .github/ISSUE_TEMPLATE/new_component.md
This is something we started filling in manually to new component issues see #487. Lets just add it to the template
> docs: Add example implementation to new_component.md

- example/yarn.lock
- package.json
- src/components/GovBanner/GovBanner.stories.tsx
- src/components/GovBanner/GovBanner.test.tsx
- src/components/GovBanner/GovBanner.tsx
- src/components/GovBanner/__snapshots__/GovBanner.test.tsx.snap
- yarn.lock
closes #456 
Verify copy changes in Storybook for .gov and .mil versions of the banner for both English and Spanish
Storybook stories:
defaults to "english" & ".gov":
with "english" and ".gov" passed:
with "english" and ".mil" passed:
with "spanish" and ".gov" passed:
with "spanish" and ".mil" passed:
> feat: Update GovBanner to match USWDS 2.8.0 release

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/new_component.md
- .github/ISSUE_TEMPLATE/request_for_implementation.md
This adds questions/fields to our issue templates asking for USWDS version where relevant. I'm hoping this will make it easier for us to determine priority of issues and map them to USWDS version milestones.
> docs: Add fields for USWDS versions to issue templates

- docs/for_trussels.md
Update the link to 'releasing documentation' to what I believe should be the correct file.
1. Browse the `for_trussels` [documentation at this commit](https://github.com/trussworks/react-uswds/blob/6e175242a786ea9565ca91bcf242654b0ad70be9/docs/for_trussels.md)
2. Click on 'releasing documentation', and confirm that you are taken to the correct doc
> docs: Update 'releasing documentation' link

- src/components/Modal/Modal.test.tsx
- src/components/Modal/Modal.tsx
Adds deprecation warnings to Modal components and functions/hooks in preparation for official removal from this library
closes #786 
(I'm now realizing this issue was still under "Needs Requirements". I figured it'd be some low-hanging-fruit to get a warning out to consumers of this library as early as possible. Whenever we're ready, this branch exists to be merged (or updated then merged) pending any requirement changes)
```
> git fetch
> git checkout bl-modal-deprecation-warning-786
> yarn storybook
```
Then preview any Modal story and take note of the console warnings (screenshots below as well)
Any single export will show a deprecation warning as follows:
---
Multiple exports will each show specific deprecation warnings
---
> feat: Add Modal deprecation warnings (non-breaking deprecation)

- src/components/GovBanner/GovBanner.tsx
- src/components/forms/Form/Form.stories.tsx
Update several state updates to use a functional update where the updated value depends on the previous value
closes #844 
Component behavior should remain unchanged by this PR.
Jest tests should still pass.
Storybook functionality (e.g. Expanding/Collapsing GovBanner or Password Reset Form, toggle `showPassword`) should still behave as expected
> fix: Use functional state update

- CHANGELOG.md
- package.json
* Add Modal deprecation warnings (non-breaking deprecation) ([#825](https://github.com/trussworks/react-uswds/issues/825)) ([41d7e8e](https://github.com/trussworks/react-uswds/commit/41d7e8e7f0be0ced8e077e51fe60f21320e79cfb))
* Add nav variant to Link component ([#846](https://github.com/trussworks/react-uswds/issues/846)) ([c92159e](https://github.com/trussworks/react-uswds/commit/c92159e08eb4b3975859942bca0378f12241e28c))
* New Component: Breadcrumb ([#804](https://github.com/trussworks/react-uswds/issues/804)) ([1a804d3](https://github.com/trussworks/react-uswds/commit/1a804d3984b6d5b4fc8cf48426e84b651587730e))
* Update GovBanner to match USWDS 2.8.0 release ([#782](https://github.com/trussworks/react-uswds/issues/782)) ([3d61f78](https://github.com/trussworks/react-uswds/commit/3d61f78 …
> chore(release): 1.11.0

- src/components/breadcrumb/BreadcrumbBar/BreadcrumbBar.stories.tsx
Simple change. While debugging https://github.com/trussworks/react-uswds/issues/869, I noticed a typo in our stories.
See correct verbiage [here](https://designsystem.digital.gov/components/breadcrumb/)
> fix: typo in storybook verbiage

- CHANGELOG.md
- package.json
* DatePicker component ([#803](https://github.com/trussworks/react-uswds/issues/803)) ([ea996c8](https://github.com/trussworks/react-uswds/commit/ea996c81287623110963bcaad3067cfb73d95144))
* prevent dependabot version updates (+ husky 5 fixes) ([#867](https://github.com/trussworks/react-uswds/issues/867)) ([4529d89](https://github.com/trussworks/react-uswds/commit/4529d899a6142dea97795f5a53016943ee16e15d))
> chore(release): 1.12.0

- CHANGELOG.md
- package.json
* Revert husky to V4 ([#923](https://github.com/trussworks/react-uswds/issues/923)) ([e934ff7](https://github.com/trussworks/react-uswds/commit/e934ff76a58cdbc523eef0a3c496fe2d20c02c73))
> chore(release): 1.12.1

- src/components/forms/CharacterCount/CharacterCount.stories.tsx
I'm currently debugging a spurious issue with emojis sometimes not
showing up in the ios-safari target on happo.io. This is an example
of such a spurious diff:
https://happo.io/a/371/p/453/compare/e934ff76a58cdbc523eef0a3c496fe2d20c02c73/cf58cd0cc54d7da04ce184d380b6f73da64a439e
My attempts at isolating this issue and reproduce haven't played out.
I've tried rendering roughly the same html as in the CharacterCount
story but all my screenshots come back with visible emoji characters.
This makes me wonder if there is maybe a race condition where Safari on
iOS is doing some optimization where a first render isn't showing emoji
(but the second/nth render does). If that's the case, adding a short
delay before Happo takes the screenshot should help resolve this.
Run in CI and see if Happo …
> fix: Add delay for CharacterCount story in Happo

- .all-contributorsrc
- README.md
- package.json
- yarn.lock
Adds Contributors section to the project README.md using the [All Contributors](https://allcontributors.org/docs/en/overview) spec and CLI. Also adds all previous contributors with the `code` emoji (this can be amended/added to).
You can add contributors (or add emoji to existing contributors) from the command line:
`yarn contributors:add <github username> <contribution type>`
This will automatically commit and push changes to the current branch. `contribution type` values are anything listed in the [Emoji Key](https://allcontributors.org/docs/en/emoji-key).
You can also ask the `@all-contributors` bot to add contributors by commenting on an issue or PR, and it will automatically open a PR ([see usage here](https://allcontributors.org/docs/en/bot/usage) and my example comment further down …
> docs: Add All-Contributors section to README

- src/components/forms/ComboBox/ComboBox.stories.tsx
- src/components/forms/ComboBox/ComboBox.test.tsx
- src/components/forms/ComboBox/ComboBox.tsx
In #901, we ensured that the combo box's `focusMode` was set to `BLUR` when a user **clicked** outside of the component. This is not sufficient for keyboard shortcuts, such as tabbing. When a user tabs through input fields, the focus on the combo box isn't reset.
*I also added an additional story that puts a text input next to the combo box to make it easier for folks to test. Since we've had some issues surrounding focus, I think it'd be good to have for testing.
#901 
#902
The form must have at least 2 elements to interact with. I used the combo box and a text input.
1. Fill in the combo box (e.g. type value, select from dropdown, etc.)
2. Use `tab` to focus the next field
3. Type in the text field
Prior to the fix, the user's focus would be shifted back to the combo box.
After the fix, …
> fix: set CombBox focusMode to BLUR when focus is outside of the component

- CHANGELOG.md
- package.json
* **ComboBox**: set CombBox focusMode to BLUR when focus is outside of the component ([#989](https://github.com/trussworks/react-uswds/issues/989)) ([fa468a0](https://github.com/trussworks/react-uswds/commit/fa468a00275c9646d43ff55fb50468c033d25ad5))
> chore(release): 1.13.1

- src/components/forms/ComboBox/ComboBox.stories.tsx
- src/components/forms/ComboBox/ComboBox.test.tsx
- src/components/forms/ComboBox/ComboBox.tsx
[ReactUSWDS Storybook](https://trussworks.github.io/react-uswds)
[USWDS](https://designsystem.digital.gov/form-controls/03-combo-box/)
This PR fixes a "keyboard trap" issue as well as other miscellaneous bugs.
1. When the user has no matching options, the user can't tab out.
2. When the user types input, no option is focused, and hits "tab", the input should clear and switch focus
3. When the user types input, and the text perfectly matches an option (case insensitive), the input should select/fill combo box with the correct option.
> fix: ComboBox "keyboard trap" and misc bugs

- .github/workflows/semantic_pr.yml
Use the [newly introduced `pull_request_target` event](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) to trigger the semantic PR workflow. This ensures semantic PR workflow is always run against the config in the base branch of a PR, allowing PRs from forks to run workflows without worrying that they are changing config. This should also fix an issue where Dependabot PRs are failing with the error: `Error: Resource not accessible by integration` ([source](https://github.com/amannn/action-semantic-pull-request/pull/24))
Note, I added this branch to the config in order to test that it [actually fixed the Dependabot issue](https://github.com/trussworks/react-uswds/pull/1013) (since `pull_request_target` means the base branch of a PR needs to …
> ci: Use pull_request_target event for semantic PR workflow

- .github/pull_request_template.md
- README.md
- docs/contributing.md
- package.json
I added some documentation to clarify the possible types and other parameters to use for our standard PR/commit format.
I also wrote some docs about how to test ReactUSWDS changes in an application, and added a note to the PR template to remind PR authors to do this testing when applicable.
> docs: Add guidance for PR titles and testing in an application

- package.json
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.test.tsx
- src/components/Button/Button.tsx
- src/components/forms/Fieldset/Fieldset.stories.tsx
- src/components/forms/Fieldset/Fieldset.test.tsx
- src/components/forms/Fieldset/Fieldset.tsx
- src/components/forms/Form/Form.stories.tsx
- yarn.lock
Bumps USWDS dependency. Additionally makes react-uswds changes to mimic [2.9.0 bugfixes and improvements](https://github.com/uswds/uswds/releases/tag/v2.9.0) 
closes: https://github.com/trussworks/react-uswds/issues/1046
Storybook and unit tests are the best bet for testing this.
Specifically, take note of the warm and cool button accent stories
Additionally, changes to Legend styles can be seen in the Fieldset stories. Old legend styles are preserved with the legendStyle="large" prop. (https://github.com/uswds/uswds/pull/3465). See note below regarding Happo
- Note: Several negligible Happo diffs due to font smoothing on buttons ,etc with 2.9.0 will be expected. One that is potentially more concerning is due to the changes to legend classes. By default, legends now render with smaller …
> feat: Update to USWDS 2.9.0

- CHANGELOG.md
- package.json
* Identifier component ([#1044](https://github.com/trussworks/react-uswds/issues/1044)) ([e79bc87](https://github.com/trussworks/react-uswds/commit/e79bc8773a3ff7d9096b8b65a9f6cb58f7d3a28a))
* StepIndicator component ([#1047](https://github.com/trussworks/react-uswds/issues/1047)) ([d61988e](https://github.com/trussworks/react-uswds/commit/d61988eb90646d35e57b17c00bd392e4ce3c200e))
* TimePicker component ([#1082](https://github.com/trussworks/react-uswds/issues/1082)) ([c7bfdee](https://github.com/trussworks/react-uswds/commit/c7bfdee95bda8c357f8b56e600e0c03be9ff922f))
* Update to USWDS 2.9.0 ([#1048](https://github.com/trussworks/react-uswds/issues/1048)) ([3859eea](https://github.com/trussworks/react-uswds/commit/3859eeaca8505403bd3bb149b12b13fb950fc082))
* Add guidance for PR titles …
> chore(release): 1.15.0

- docs/adr/0000-template.md
- docs/adr/0001-update-major-version-with-uswds-minor-version.md
- yarn.lock
Adds an ADR to help us decide ReactUSWDS versioning as it relates to USWDS versions.
I also copied the ADR template @brandonlenz introduced in https://github.com/trussworks/react-uswds/pull/1026
Resolves #343
> docs(adr): Increase ReactUSWDS version when updating USWDS version

- README.md
- Added a line about matching USWDS version to the README Usage section, and moved the Background section further down
- Added a badge that will show our current version of USWDS
- Fixed the CircleCI badge (was pointing to the wrong branch)
> docs: Update usage in readme, add USWDS version badge

- package.json
- src/components/Identifier/Identifier/Identifier.stories.tsx
- src/components/Identifier/Identifier/Identifier.test.tsx
- src/components/Identifier/IdentifierGov/IdentifierGov.test.tsx
- src/components/Identifier/IdentifierGov/IdentifierGov.tsx
- src/components/Identifier/IdentifierGov/__snapshots__/IdentifierGov.test.tsx.snap
- src/components/Identifier/IdentifierIdentity/IdentifierIdentity.test.tsx
- src/components/Identifier/IdentifierIdentity/IdentifierIdentity.tsx
- src/components/Identifier/IdentifierLogos/IdentifierLogos.test.tsx
- src/components/Identifier/IdentifierLogos/IdentifierLogos.tsx
- src/components/Identifier/IdentifierMasthead/IdentifierMasthead.test.tsx
- src/components/Identifier/IdentifierMasthead/IdentifierMasthead.tsx
- src/index.ts
This PR implements two subcomponents `IdentifierIdentity` and `IdentityLogos` in order to prevent our users from having to manually apply [USWDS Identity component](https://designsystem.digital.gov/components/identifier/) classes.
closes #1100 
Check out this branch and run `yarn test` to execute tests and `yarn storybook` to see the new component in action.
Alternatively, you can scroll to the bottom of this page and click "Show environments" on the right above the comment input box to access this component in Storybook. 
These changes are completely abstract, we are merely adding more structure to the code.
> feat: Implement Identifier subcomponents

- src/components/grid/Grid/Grid.tsx
I'm pretty sure we tried almost exactly this a few days ago, but I just gave it another shot and it looks like it works!! 
This resolves an issue in https://github.com/trussworks/react-uswds/pull/1166 where the omitted props were being spread to the custom rendered element.
> Update isCustomProps to accept "otherProps"

- CHANGELOG.md
- package.json
* Checkbox Tile Variant ([#1104](https://github.com/trussworks/react-uswds/issues/1104)) ([9936c4a](https://github.com/trussworks/react-uswds/commit/9936c4ad6d53cd49f52fb6b7a0f52b752eb15317))
* Implement ProcessListHeading subcomponent ([#1162](https://github.com/trussworks/react-uswds/issues/1162)) ([964e34c](https://github.com/trussworks/react-uswds/commit/964e34cb831554f5951973a62a5d4959357daff3))
* New Component ProcessList MVP ([#1107](https://github.com/trussworks/react-uswds/issues/1107)) ([1bc0f93](https://github.com/trussworks/react-uswds/commit/1bc0f93f916ce46470230b34406fef57c3e44a16))
* New Component SiteAlert ([#1099](https://github.com/trussworks/react-uswds/issues/1099)) ([c1e88e0](https://github.com/trussworks/react-uswds/commit/c1e88e0e5fcdcd8c1612943d6808c8ec5ff2efd5))
* …
> chore(release): 1.17.0

- .circleci/config.yml
- jest.config.js
Adds the `coverageThreshold` config value to the Jest config for this project, with the minimum global values for statement, branch, function, and line coverage set to (slightly below) their current values. These can be raised over time if we want.
Changes the `yarn test` task in the CircleCI build script to also collect test coverage; similar to a test failure, this will fail the build if the test coverage drops beneath any of the aforementioned threshold values.
Closes #75 
* Did *this* pull request's CircleCI "build" check fail? If so, that would be a problem
* Run `yarn test:coverage` and verify that the process exits with code 0. In the `jest.config.js` file, change any of the `coverageThreshold` values to `100`, run `yarn test:coverage` again and verify that the process exits with …
> build(circleci): Collect test coverage and require a minimum coverage threshold

- .circleci/config.yml
- package.json
- src/components/forms/FileInput/FilePreview.tsx
- src/serverSideTest.js
The `forms/FileInput/FilePreview.tsx` sub-component was importing a string from a constants file; this caused Webpack to include all exported variables in that file in the final build. This meant that uses of the `File` web-only API were included in said build, which caused server-side site generation (such as Next or Gatsby) to throw a ReferenceError when importing this package, as those are running in a node-only context where that API doesn't exist.
The simple fix was to move the value of that constant into the FilePreview subcomponent, which prevents the entire constants file from being included in a webpack build.
This PR also adds:
1. A very simple e2e test (`/src/serverSideTest.js`) to check for package importability -- it just `require`s the version of the local version of the …
> fix: Package crash on server-side import

- src/components/forms/ComboBox/ComboBox.stories.tsx
- src/components/forms/ComboBox/ComboBox.test.tsx
- src/components/forms/ComboBox/ComboBox.tsx
- src/components/forms/ComboBox/useComboBox.ts
This changes the `ComboBox` component to use `forwardRef` and the `useImperativeHandle` hook. It allows users to pass in a ref to a component instance and then call a `clearSelection` method on it, which will clear any existing value.
This change is _deeply_ indebted to the pattern established in PR #1165.
As this changes an existing component to use `forwardRef`, this should be considered a BREAKING CHANGE.
Closes #1137 .
In the application, try passing a `ref` to the ComboBox component, selecting a value for the component, and using `ref.current.clearSelection()` to reset the value.
> feat!: Expose ComboBox component ref with a clearSelection method

- .happo.js
Disable edge browser in happo because it has too many false positives
> build(happo): disable edge browser because of false postives

- .github/workflows/deploy-storybook.yml
- Release on any numeric tag push. 
- [fix] Deployed storybook is not up to date
closes #1357 
We will probably need to release 2.0.1 and push a tag
> build(storybook): release on any numeric tag push

- CHANGELOG.md
- package.json
Failed release - `yarn build` is is throwing an error.  We will fix and then retry release at this tag.
Reverts trussworks/react-uswds#1588
> chore: Revert "chore(release): 2.1.0"

- .all-contributorsrc
- README.md
Adds @jenbutongit to all-contributors. I forgot to recommend that they add it in https://github.com/trussworks/react-uswds/pull/1687/
- check that @jenbutongit is added to the all-contributors readme
> docs: Add Jen Duong as a contributor

- CHANGELOG.md
- package.json
* Allow intrinsic elements to be passed to Fieldset ([#1862](https://github.com/trussworks/react-uswds/issues/1862)) ([85a0092](https://github.com/trussworks/react-uswds/commit/85a0092bad776357ede2cd4e9aee9a5aa11912fd))
---
[compare](https://github.com/trussworks/react-uswds/compare/2.4.1...release-2.5.0)
> chore(release): 2.5.0

- src/components/stepindicator/StepIndicator/StepIndicator.stories.tsx
- src/components/stepindicator/StepIndicator/StepIndicator.test.tsx
- src/components/stepindicator/StepIndicator/StepIndicator.tsx
The heading level in the StepIndicator currently defaults to `h4`, and the inability to change this causes an accessibility issue when used in a document that doesn't include `h1`, `h2`, and `h3`.  We should be able to specify the desired heading level.
This PR introduces a `headingLevel` prop to the StepIndicator, so that any given instance can have any valid heading level. 
In order to make this a non-breaking change, if no heading level is specified, the component maintains the current behavior of defaulting to `h4`.
Closes #1751 
In Storybook, select the Heading variant of the StepIndicator, and inspect the markup to see that it accords with the screenshot below.
Review new unit tests.
> feat: accept prop for heading level (#1751)

- src/components/forms/ComboBox/ComboBox.stories.tsx
- src/components/forms/ComboBox/ComboBox.test.tsx
- src/components/forms/ComboBox/ComboBox.tsx
- src/components/forms/ComboBox/useComboBox.ts
- src/index.ts
Adds a `focus` method to the ComboBox ref that focuses on the underlying text input element.
Closes #1875 
- In Storybook: view the **Combo box / Exposed Ref Methods** story and click on the "Focus on input" button to verify the text input has focus
- In an application: render the `<ComboBox>` component with a forwarded ref and call `ref.current.focus()` to focus on the text input.
- See https://github.com/USSF-ORBIT/ussf-portal-client/pull/478/files#diff-057c5f93639ae6992d18848a5acdcd2301f2de84a529488bc89cc228b58492f5 for example usage
> feat: Add focus method to ComboBox ref

- .github/workflows/build-and-test.yml
- package.json
Add support for Node 16 (pushed to internal branch from forked PR)
Internally branched PR for @epicfaace's change in https://github.com/trussworks/react-uswds/pull/1743/ to allow our CI to run.
> Fixes #1582, so that users with node 16 can install this package.
> build(node): Support Node 16

- docs/releasing.md
First time running through the tarbell release process  with @rswerve . We noticed one typo (with `unzip artifact.zip`) and there were a couple points were more context might be good. Otherwise the docs seemed ⭐ !
I also moved the longer <describe> block content into a lower section simply called HELP 😆
> docs: Add help section to releasing README

- CHANGELOG.md
- package.json
* Add focus method to ComboBox ref ([#1876](https://github.com/trussworks/react-uswds/issues/1876)) ([c380a94](https://github.com/trussworks/react-uswds/commit/c380a94c3c7dd2ae363fd0f58e80d93aa35cc43b))
* Fix Tooltip positioning ([#1878](https://github.com/trussworks/react-uswds/issues/1878)) ([f15fea0](https://github.com/trussworks/react-uswds/commit/f15fea0b2ce037b48b8860e69a074de30aabfa91))
* Add help section to releasing README ([#1867](https://github.com/trussworks/react-uswds/issues/1867)) ([73e9094](https://github.com/trussworks/react-uswds/commit/73e9094a82033bdee643316ff4db91a8460d999b))
> chore(release): 2.7.0

- .eslintrc
- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.test.tsx
- src/components/Modal/Modal.tsx
This fixes #1886 by using a Portal to render modals outside the application root by default.
The root cause is that when we mark elements in the page with `aria-hidden` as a part of opening a modal, it prevents the modal and its contents from appearing in the accessibility tree since they appear as children of elements that are now hidden.
This means that users with JAWS can’t interact with the modal using the keyboard. Without JAWS running, the keyboard works properly. This is also how we missed it for so long
I was able to reproduce the issue both in Managed Care’s app and react-uswds storybook.
The original USWDS modal’s JS assumes that the modal will appear outside the rest of the app, usually at the top level of the document body. This PR uses a Portal to accomplish something …
> fix: Render modal outside app root by default.

- CHANGELOG.md
- package.json
* Render modal outside app root by default. ([#1890](https://github.com/trussworks/react-uswds/issues/1890)) ([0828351](https://github.com/trussworks/react-uswds/commit/082835186f8ba7d10941f2425e6db1570c57c9dd))
> chore(release): 2.7.1

- docs/contributing.md
- src/components/Modal/Modal.test.tsx
- src/components/Modal/Modal.tsx
I fixed this issue by consolidating some of the code that handles DOM changes when the modal is opened & closed, and explicitly resetting body padding when its closed instead of toggling between the two values.
I also added to the docs about how to use `yarn link` to test the library locally with a NextJS app.
Fixes #1898 
* You can test this on an application that uses the Modal component by causing the modal to mount & unmount (typically by navigating to a new page). Without this fix, the padding-right on the body element would continue to increase by 15px (or the width of your scrollbar)
* Tested & verified on [Space Force](https://github.com/USSF-ORBIT/ussf-portal-client)
* I also added a test case for this that was failing without the fix.
> fix: Fix modal causing body padding to increase when unmounted

- CHANGELOG.md
- package.json
* Fix modal causing body padding to increase when unmounted ([#1899](https://github.com/trussworks/react-uswds/issues/1899)) ([fb46e88](https://github.com/trussworks/react-uswds/commit/fb46e8867f61781edf3393a359236bbcc45c626f))
> chore(release): 2.7.2

- CODEOWNERS
- README.md
- docs/for_maintainers.md
- docs/for_trussels.md
- docs/prerelease.md
- Add for_maintainers.md doc
- Update for_trussels.md doc accordingly
- Make "Active Maintainers" TBD on README as we start rotating responsibilities 
- Update CODEOWNERS to remove non-trussels
- Move pre-release docs to its own file to have less content on the main README
> docs: Add maintainer docs as per TDR 95

- package.json
- yarn.lock
The previous versions of Danger did not allow it to run in macOS
Monterey. See this Slack thread and GitHub issue for more information.
=> [Slack thread](https://trussworks.slack.com/archives/C0122MPMXL3/p1646761007425309?thread_ts=1646760740.618919&cid=C0122MPMXL3) 🔒 
=> GitHub issue https://github.com/danger/danger-js/issues/1187
- danger/danger-js#1187
Run `yarn danger local -b main --failOnErrors` on a branch that you were previously unable to and it should now succeed rather than present a `TypeError` involving `macosRelease`.
> fix: Update the version of Danger to allow for prepush

- src/stories/templates/documentation.stories.tsx
closes https://github.com/trussworks/react-uswds/issues/1914
> fix(docs): Fix typo in Storybook documentation template #1914

- src/components/Tooltip/Tooltip.stories.tsx
- src/components/forms/DatePicker/DatePicker.stories.tsx
Hopefully resolves some spurious diffs we see on almost every PR with tooltips and occasionally with default value DatePicker.
First test will be making sure that happo completes correctly on this branch/PR. It is somewhat unclear how beforeScreenshot and waitFor play together if used simultaneously.
There may also still be happo diffs on this PR (I expect it in fact). I don't think the issue will be resolved until the base branch _and_ PR branches both have this code. 
https://docs.happo.io/docs/storybook#waiting-for-content
> ci: Improve Happo Consistency

- src/components/Tooltip/Tooltip.stories.tsx
Exclude Happo from checking Tooltip on ios-safari, which has frequently caused problems with ci checks
> ci: exclude ios-safari from happo on Tooltip

- CHANGELOG.md
- package.json
* Add ability to pass through StepIndicator heading props ([#1895](https://github.com/trussworks/react-uswds/issues/1895)) ([3830814](https://github.com/trussworks/react-uswds/commit/383081423f0cf2d5f0d982c7486833d24aed3730))
* Adds headingLevel prop for Alert component ([#1928](https://github.com/trussworks/react-uswds/issues/1928)) ([ce6de61](https://github.com/trussworks/react-uswds/commit/ce6de61eeb072e3af346b89e808e0305114e59fa))
* Deprecate default heading levels ([#1947](https://github.com/trussworks/react-uswds/issues/1947)) ([512a901](https://github.com/trussworks/react-uswds/commit/512a901d63a1a59739df12899454e6425e8ad9d0))
* **docs:** Fix typo in Storybook documentation template [#1914](https://github.com/trussworks/react-uswds/issues/1914) …
> chore(release): 2.9.0

- .happo.js
- example/yarn.lock
- package.json
- yarn.lock
Hi there! Henric from Happo here. 
@Igarfinkle reached out to me to inform me that your Happo jobs were timing out. I've had a look at some of the recent failures and have found them to be caused by unstable and slow execution times in Internet Explorer. With IE going away soon (June 15th is the official date from Microsoft), we've found it increasingly hard to keep IE up and perform well. Recent Windows updates push Edge pretty hard, and it looks like they've even made IE deliberately slower (although I have no concrete numbers to back this up...). 
In this PR, I'm taking care of a few things: 
- Upgrade to latest happo.io library
- Re-enable Edge (should be more stable at this point)
- Split up IE jobs in three chunks
I initially came here with the intention to remove IE from …
> fix: Happo updates

- .kodiak.toml
Adds a label association for Kodiak to prioritize PRs in its automerge queue
https://kodiakhq.com/docs/config-reference#mergepriority_merge_label
> feat(ci): add automerge priority label for Kodiak

- src/components/forms/DatePicker/DatePicker.stories.tsx
Expects to find `MM/DD/YYYY` in Happo screenshots instead of `YYYY-MM-DD`
Even though the component returns the selected date in `yyyy-mm-dd` format, it displays as `mm/dd/yyyy`, so I believe we should use that format in the `waitforcontent` preceding the happo check.
> ci: change expected date format for DatePicker in Happo

- src/components/forms/ComboBox/ComboBox.test.tsx
Noticed some Combobox tests were throwing warnings that there were overlapping act events. Likely related to `userEvent` upgrade since `userEvent`s are wrapped in `act`, and they're all supposed to be async/awaited in the newest version. Found a few that were not, so I updated those here and the warnings have been silenced :)
`yarn test` and verify no output for Combox relate to overlapping `act` events exists
> chore(tests): Use await on all userEvents

- src/stories/templates/createaccount.stories.tsx
- src/stories/templates/landing.stories.tsx
- src/stories/templates/notfound.stories.tsx
- src/stories/templates/signin.stories.tsx
This PR originally due to @svalexander. It was recreated by a Truss employee so it could pass the build checks. 
This pr adds a 404 page not found example to the ReactUSWDS Storybook like the one seen in USWDS' documentation. As many of the elements of the template already existed in the documentation template and the authentication templates I borrowed chunks of code from those examples and updated with the appropriate changes. 
https://github.com/trussworks/react-uswds/issues/1619
* Run "yarn storybook" to start Storybook locally. 
* Can verify addition of template by navigating to "page templates > not found page". 
* Can then compare template addition with the USWDS 404 example found [here](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develo …
> docs: 404 page template added

- CHANGELOG.md
- package.json
* Fixes an issue where Type definitions were not properly packaged [#2053](https://github.com/trussworks/react-uswds/issues/2053) [febcd65](https://github.com/trussworks/react-uswds/commit/febcd65d1d2bf8ff84f558b4d14013ba8328cc38)
---
[Compare](https://github.com/trussworks/react-uswds/compare/3.0.1...release-3.0.2)
> chore(release): 3.0.2

- .github/workflows/build-and-test.yml
- package.json
Node@12 has reached end of life and is no longer maintained. Node@18 was just released as the current version of Node. This PR replaces Node@12 with Node@18 in our build tests
> ci: Support Node@18

- .github/dependabot.yml
I find being automatically added to dependabot reviews to be too noisy and clogs my notifications where I try to stay on top of project work.
I'm keenly aware that we get ~20+ dependency updates on a regular weekly basis that usually require manual intervention, so the review requests only add noise that is distracting. When I have time to come push things along, I do so and will continue to do so regardless of whether I'm tagged on the dependabot PRs or not
> chore: Remove myself from dependabot review requests for this repo

- dangerfile.ts
This patch series adds better checking for Danger verifying if contributors was modified by only checking the JSON Diff. If there's not contributor object, then there is no change and move on. This eliminates all the false positives we've seen in recent PRs around modifying the package.json file near the word contributors.
You can create a new branch locally and modify the package.json with a contributors stanza. Then commit it and run the following Danger command to trigger it.
```
yarn danger local -b main --failOnErrors
```
> fix: Danger contributors check

- .github/dependabot.yml
- CODEOWNERS
Removes Suz from stuff that automatically assigned her to things
@suzubara of course, being an open source project, we welcome your contributions should you ever feel like taking a trip down memory lane with react-uswds in the future!
> chore: Remove Suz from CODEOWNERS and dependabot.yml

- src/index.ts
PR to merge #2210 from @sawyerh
The `IconListContent` and `IconListIcon` components weren't available to import from "@trussworks/react-uswds", but they [appear to be required in order to use IconList](https://trussworks.github.io/react-uswds/?path=/story/components-icon-list--default).
> fix: Export IconListContent and IconListIcon

- package.json
- yarn.lock
See open Dependabot vulnerabilities for `url-parse`
`yarn test` passes locally
> chore: address url-parse vuln

- package.json
- yarn.lock
Addresses open `json-schema` vuln reported by Dependabot
`yarn test` passes locally
> chore: update json-schema to address open vuln

- CHANGELOG.md
- package.json
Various dependency updates, including ones to resolve critical security warnings
[Preview differences since 4.1.0](https://github.com/trussworks/react-uswds/compare/4.1.0...9d0e5c5229b1f6b744c52fd29a6e935e598b6d9f)
> chore(release): 4.1.1

- .github/workflows/build-and-test.yml
- .github/workflows/deploy-storybook.yml
To make it easier to approve 3rd party PRs and debug the build checks, this PR is making it so we can manually trigger the build checks workflow.
Also allow manual trigger of storybook deploy to allow for debugging of that workflow when changes are needed.
Not possible until merged, sadly.
> build: allow manual triggering of build checks

- .all-contributorsrc
- src/components/forms/FileInput/FileInput.tsx
`navigator` is only available in a browser environment, and calling it on the server causes an exception. 
Checking if `navigator` is defined isn't enough however, since that causes a different React error:
```
Error: Text content does not match server-rendered HTML.
See more info here: https://nextjs.org/docs/messages/react-hydration-error
```
To resolve both issues, I've followed the suggestion in the link above, to run the check in `useEffect`.
Resolves #2366
I tested this locally with a Next.js app by:
1. Running `yarn build`
1. Running `npm link` in the library's directory
1. Running `npm link @trussworks/react-uswds` in the Next.js project
1. Rendering `FileInput` in the Next.js project
1. Running `npm run dev` in the Next.js project and confirming no errors occur
> fix: Fix FileInput in SSR

- src/components/forms/DatePicker/DatePicker.stories.tsx
- src/components/forms/DatePicker/DatePicker.test.tsx
- src/components/forms/DatePicker/DatePicker.tsx
Adds validation styles (and corresponding story) to DatePicker component, which uses a standard `<input>` instead of our input component, which already has that validation.
Resolves #2263 
1. Open http://localhost:9009/?path=/docs/components-date-picker--complete-date-picker
2. Check each `validationStatus` control
> fix: Adds validation styles to datepicker

- src/components/forms/Dropdown/Dropdown.test.tsx
- src/components/forms/Dropdown/Dropdown.tsx
- src/components/forms/Select/Select.tsx
Batched PR feedback/suggestions for #2415 
Unit tests, storybook
Dropdown still works, and displays deprecation warning:
Select of course also works, does not display deprecation warning:
> Select Deprecation edits

- src/components/forms/FileInput/FileInput.stories.tsx
- src/components/forms/FileInput/FileInput.test.tsx
- src/components/forms/FileInput/FileInput.tsx
Adds property to FileInput component to allow error text inside component to be customized. Before, it was hardcoded making it inappropriate for mobile and non-English contexts.
Resolves #2456
* Give custom text to `errorText`
* Ensure all other file input functions behave as before
* Or run storybook, go [here](http://localhost:9009/?path=/story/components-file-input--custom-text) and try drag-dropping anything to the field
> fix: added error param, test, story

- .github/workflows/release-please.yml
Forgot to turn off the option that adds a v to the version tag name. Disabling it because we haven't been having one in the past and didn't want to change the pattern.
> build: disable include-v-in-tag option

- src/components/header/NavCloseButton/NavCloseButton.tsx
`<svg>` elements with an `img` role must have an alternative text: https://dequeuniversity.com/rules/axe/4.6/svg-img-alt?application=msftAI
This issue was introduced in https://github.com/trussworks/react-uswds/pull/2411, and began failing a11y tests in our project when 5.0.0 was released.
1. Open the `NavCloseButton` Storybook page
2. Change your viewport size so the button shows
3. Run an accessibility scanner like https://accessibilityinsights.io/
Before:
After:
> fix: Set alternative text on SVG img icon in menu close button

- src/components/Alert/Alert.stories.tsx
- src/components/Alert/Alert.test.tsx
Adds a story for the `<Alert>` component showing use of the `validation` prop.
Currently none of the stories make use of this prop and for documentation purposes, it's a good idea to demonstrate this. I've lifted the content [from the Validation component from USWDS](https://designsystem.digital.gov/components/validation/).
1. `yarn run storybook`
2.  Go to: http://localhost:9009/?path=/story/components-alert--with-validation
> fix: Adds story using validation prop for Alert component

- src/styles/_overrides.scss
- src/styles/index.scss
Thanks to Joe, this establishes a pattern for us to replicate in using utilities, at least in the root styles folder
None
Add any future override styles to the new _overrides.scss file
> fix: moved overrides to let us use utilities

- CODEOWNERS
This PR adds the `react-uswds-admin` github team as code owners to make that easier to manager. Also adds the `react-uswds-design-owners` team as owners of the storybook files. This is to facilitate having a designer provide input on changes that affect the look and feel of a component.
> chore: add admin group and design owners group

- README.md
- package.json
See github issue
- https://github.com/trussworks/react-uswds/pull/2572#issuecomment-1719755291
- resolves: #2598
> feat(deps): Allow consumers to use newer uswds minor versions

- docs/design-pr-reviews.md
Adds documentation about reviewing front end PRs for designers & non-engineers
> docs: add design PR review documentation

- src/components/forms/FileInput/FileInput.stories.tsx
Associates label with the right input using `htmlFor` in `withError` story of file input. 
closes #2609 
1. Launch storybook and navigate to with error story of file input
2. Click open canvas in new tab button to open this story in a new tab
3. Run automated accessibility checker of choice on the page that opens to check for `Form elements should have labels` issue
4. Should not see any `Form elements should have labels`
> fix: Updates file input stories to set appropriate html for value of label

- .all-contributorsrc
- README.md
Add @AnnaGingle to contributor list... done via CLI since all-contributors bot is not working.
Anna's orig pr: https://github.com/trussworks/react-uswds/pull/2633
broken bot pr: https://github.com/all-contributors/app/issues/485
> docs: add @AnnaGingle as a contributor

- README.md
Yarn scripts links(under the Quick links in the Contributing section) were not properly configured due to which clicking on the link would take us to a page that was not present in the repository. 
This fix solves the issue
Closes #2645
1. Go to the Readme file
2. Scroll down to Contributing -> Quick Links
3. Click on Yarn scripts
4. See contributing.md document is opening
> fix: readme quick links

- src/components/header/NavCloseButton/NavCloseButton.tsx
Closes #2639 
I tested with `yarn link` to an application using playwright, AXE, and HTML_CodeSniffer. I am yet not familiar enough with these packages to set up an example repo, but I can confirm that these changes address our E2E testing issues.
> fix(a11y): move aria-label from svg icon to button

- webpack.config.js
This adds the [`"use client"`](https://react.dev/reference/react/use-client) directive to the transpiled JS module to support apps utilizing [React Server Components](https://nextjs.org/docs/app/building-your-application/rendering/server-components):
Some context from the React docs on this directive:
> When a file marked with 'use client' is imported from a Server Component, [compatible bundlers](https://react.dev/learn/start-a-new-react-project#bleeding-edge-react-frameworks) will treat the module import as a boundary between server-run and client-run code.
> For apps that use React Server Components, the app is server-rendered by default. 'use client' introduces a server-client boundary in the [module dependency tree](https://react.dev/learn/understanding-your-ui-as-a-tree#the-module-de …
> feat: Add “use client” to fix React Server Components

- src/components/InPageNavigation/InPageNavigation.stories.tsx
- src/components/forms/Label/Label.stories.tsx
Github PRs were displaying some linting warnings about these files, this PR resolves them.
e.g:
> chore: Fix reported unused imports

- .github/dependabot.yml
- CODEOWNERS
Fixes dependabot error adding reviewer who is now no longer part of Truss org (https://github.com/trussworks/react-uswds/pull/2670#issuecomment-1827155093).
We opted to not have codeowners/reviewers for dependabot PRs. Folks tend to just look at open PRs to investigate/prod dependabot along. The signal to noise ratio is too low
New dependabot PRs after merging this should not have the reviewer error, but no way to test before.
> chore: Remove dependabot reviewers

- package.json
- src/components/Icon/Icon.stories.tsx
- src/components/Icon/Icons.stories.tsx
- src/components/Icon/Icons.ts
- src/components/Identifier/Identifier/Identifier.stories.tsx
- src/components/Identifier/Identifier/Identifier.test.tsx
- src/components/Identifier/IdentifierIdentity/IdentifierIdentity.test.tsx
- src/components/Identifier/IdentifierMasthead/IdentifierMasthead.test.tsx
- src/components/Modal/Modal.test.tsx
- src/components/Modal/Modal.tsx
- src/components/forms/DatePicker/Calendar.tsx
- src/components/forms/DatePicker/DatePicker.test.tsx
- src/components/forms/DatePicker/DatePicker.tsx
- src/components/forms/DatePicker/i18n.ts
- src/components/forms/RangeInput/RangeInput.stories.tsx
- src/components/forms/RangeInput/RangeInput.test.tsx
- src/components/forms/RangeInput/RangeInput.tsx
- src/stories/templates/createaccount.stories.tsx
- src/stories/templates/mutliplesignin.stories.tsx
- src/stories/templates/notfound.stories.tsx
- src/stories/templates/signin.stories.tsx
Resolves #2682
The following changes in the 3.7 and 3.7.1 updates involved more than just scss updates. Changes that are checked off have been committed to this PR; the others are available for others to contribute updates to (or remove if no update is needed):
**edit**: this one was actually a USWDS-specific implementation change, no change needed for us
**edit**: this was also a USWDS-specific refactor, but I did add the console errors from here
> feat: updates for USWDS v3.7

- README.md
- docs/for_maintainers.md
- Rotates the maintainer for the new term!
- Also removes a statement in the maintainer docs that is no longer correct. Fortunately, our CI can now run successfully on 3rd party PRs
> chore: Rotate maintainer

- src/components/banner/BannerIcon/BannerIcon.tsx
- src/components/banner/GovBanner/__snapshots__/GovBanner.test.tsx.snap
- src/components/header/NavCloseButton/NavCloseButton.tsx
> fix: Remove image role attribute from Banner Icon component

- src/components/stepindicator/StepIndicator/StepIndicator.stories.tsx
- src/components/stepindicator/StepIndicator/StepIndicator.test.tsx
- src/components/stepindicator/StepIndicator/StepIndicator.tsx
- yarn.lock
Parametrized strings in StepIndicator component to allow translation of "Step" and "of" strings. 
There are still more English strings hard coded in the StepIndicatorStep subcomponent, as well as other components, but this narrow improvement is to allow for a client project to proceed. I will continue pushing for resources to prioritize an i18n strategy (see https://github.com/trussworks/react-uswds/issues/1742)
Resolves #2705 
- Run new tests
- Use storybook controls and inspect 👇
> feat: parametrized StepIndicator strings

- src/components/InPageNavigation/InPageNavigation.test.tsx
- src/components/Modal/Modal.test.tsx
- src/components/Modal/ModalCloseButton/ModalCloseButton.test.tsx
- src/components/Modal/ModalOpenLink.test.tsx
- src/components/Modal/ModalToggleButton.test.tsx
- src/components/forms/ComboBox/ComboBox.test.tsx
- src/components/forms/DatePicker/Calendar.test.tsx
- src/components/forms/DatePicker/DatePicker.test.tsx
- src/components/forms/DatePicker/Day.test.tsx
- src/components/forms/DatePicker/MonthPicker.test.tsx
- src/components/forms/DatePicker/YearPicker.test.tsx
- src/components/forms/DateRangePicker/DateRangePicker.test.tsx
- src/components/forms/FileInput/FileInput.test.tsx
- src/components/forms/TextInputMask/TextInputMask.test.tsx
- src/components/forms/TimePicker/TimePicker.test.tsx
Fixes a bunch of userEvents imports' lint warnings (`import/no-named-as-default`)
None
`yarn lint` should not yield any warnings
> fix: fixed lint warnings

- README.md
- docs/contributing.md
This addresses one of #2265's ACs, removing two references to CircleCI, including the glaring red "failing" badge on our readme:
After merging this PR, update #2265 to be focused just on documenting GH Actions
Addresses half of #2265
Closes #2604
> docs: removed circleci references

- .github/dependabot.yml
Updates the dependabot configuration to group relevant dependencies together to reduce the number of individual PRs created and to ensure dependencies that need to be updated simultaneously are done so to prevent errors.
#2832
> build: dependabot groups

- .github/workflows/deploy-storybook.yml
Changes the github action used for storybook deployment to one suggested by Storybook in their documentation on deployment to Github Pages (see: https://storybook.js.org/docs/sharing/publish-storybook#github-pages) in order to hopefully resolve errors in the current storybook deployment.
> ci: change action used for storybook deploy

- src/components/InPageNavigation/InPageNavigation.module.scss
- src/components/InPageNavigation/InPageNavigation.test.tsx
- src/components/InPageNavigation/InPageNavigation.tsx
Fixes leak of smooth-scroll, limits it just to pages where component is being used
Also changed a variable to be more descriptive
Resolves #2867
Use storybook as an example, comparing the [live version](https://trussworks.github.io/react-uswds/?path=/docs/components-in-page-navigation--docs) (where smooth-scroll is applied on all pages after loading the component) vs what you can build locally, shown below:
> fix: moved smooth-scroll application to useEffect

- src/components/stepindicator/StepIndicator/StepIndicator.stories.tsx
- src/components/stepindicator/StepIndicator/StepIndicator.test.tsx
- src/components/stepindicator/StepIndicator/StepIndicator.tsx
- src/components/stepindicator/StepIndicatorStep/StepIndicatorStep.test.tsx
- src/components/stepindicator/StepIndicatorStep/StepIndicatorStep.tsx
Incorporates the option to use i18n for screen-reader only text regarding the status of each step in the StepIndicator. Updates tests and storybook.
Closes #2857 
`yarn storybook`
In the 'Controls', create a `statusText` object (ex. {complete: "completado", incomplete: "no completado"}). 
Using a screen reader, listen to the stated status of each step. 
AND/OR
Look at the source code in the developer tools for each of the steps and see the sr-only element with the applied status text.
> fix: add a statusText prop to StepIndicator to allow for i18n for the sr-only element Closes #2857

- vite.config.ts
This fixes usage of the package in a React Server Components environment (Next.js app router). This regression was introduced during the [Webpack -> Vite migration](https://github.com/trussworks/react-uswds/commit/17dde0a03c6c23b2e145b78ee8ef3faf86867431).
1. `npx create-next-app@latest` - select Yes for App Router when you get there
2. Add a React USWDS component to a page
> fix: ‘use client’ directive syntax

- src/components/Accordion/Accordion.test.tsx
- src/components/Accordion/Accordion.tsx
- src/index.ts
Users pass in items to the Accordion component and those items could have custom onClick handlers that fire via the `handleToggle` prop. (For example, custom GA tracking events described in the below issue.) This change actually implements firing those passed-in functions.
addresses #2739 
In `Accordion.stories.tsx`, add a line to the first item in the `testItems` array:
```
handleToggle: () => {
console.log('hello')
},
```
Open one of the Accordion stories in Storybook, open the developer console, click the first Accordion item and you should see "hello" appear.
> feat: Enable custom on click handler passed via accordion item

- src/components/forms/TextInput/TextInput.test.tsx
- src/components/forms/TextInput/TextInput.tsx
Currently this component forwards refs in a way that does not work in new versions of react and I'm not sure if it ever worked in any version of react. Leaving the old way in case somebody is using it.
> fix: Update TextInput ref forwarding

- src/components/Tooltip/Tooltip.tsx
Alternate approach to #2562, which does not change the API of the `Tooltip` component. Use React's `useId` to generate a unique identifier instead of a random number. 
This is the expected way to generate IDs, so plays nicely with server side rendering frameworks and is easy to mock for unit or snapshot tests.
Example of jest config for mocking
```
// Make sure the auto-generated IDs are stable for snapshot testing
jest.mock("react", () => ({
...jest.requireActual("react"),
useId: () => "r:id",
}));
```
This is a pure bugfix/refactor. It makes no change to API or UI
> fix: useId instead of random number for tooltip ID

- src/components/forms/Form/Form.stories.tsx
Move form templates in Storybook from the `Components` section to the `Page Templates` section.  
Also move `Text input` out of `Forms` into `Components`, to match the location of other inputs.
This should only affect Storybook documentation, not any projects that use `react-uswds`.
This closes #2620 
You can test locally with `npm run storybook`. This should open your local build in your default browser, or you can navigate to http://localhost:9009/  
In the sidebar navigation, there is a new folder named "Forms" under the heading "Page Templates". This contains:
- Name Form
- Address Form
- Sign In Form
- Password Reset Form
Also note that "Text input" is now just inside the "Components" heading (instead of nested under "Components > Form templates").
> fix: #2620 Move form templates in Storybook

- .github/workflows/package-release.yml
- .github/workflows/publish-next.yml
- eslint.config.cjs
- src/serverSideTest.js
The `--prefer-offline` flag for installing dependencies via Yarn is deprecated in favor of `yarn add --cached`.
This is related to #2878 (we forgot to update this flag).
This should be reflected in CI tests, though running `yarn install` on your local should produce an error on `main`, and not produce an error on this branch.
I've also made updates to the eslint config, so run `yarn lint`.
> chore: update Yarn CI flag

- .github/workflows/build-and-test.yml
- .github/workflows/publish-next.yml
- package.json
- yarn.lock
PR #3110 somehow came through with no changes. This includes the changes that should have been made with that PR:
More updates to yarn. This swaps out the --frozen-lockfile flag and removes the yarn v1 dependency.
--immutable errors when the lockfile changes.
--immutable-cache errors when the cache changes.
This is a continuation of #3109
> chore: update yarn ci

- .github/workflows/build-and-test.yml
- .github/workflows/deploy-storybook.yml
- .github/workflows/package-release.yml
- .github/workflows/publish-next.yml
- .github/workflows/release-please.yml
We've been seeing `Error: The operation was canceled.` on CI tests, with no clear indication of why. On investigation, it appears there are several possible causes (including configurations on GitHub's side), but one is the GH CI [`fail-fast` strategy](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast).
> GitHub will cancel all in-progress and queued jobs in the matrix if any job in the matrix fails. This property defaults to true.
Setting `false` may solve this problem, but it will also surface all failing tests at once instead of making us fix them one at a time.
I think we just have to merge this one and let it run. Check out [the documentation](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-gith …
> chore: set CI fail-fast to false

- src/components/Tooltip/Tooltip.tsx
Cleanup based on PR feedback to #3094 
Use hooks properly (per react's rules of hooks) in generating and using the ID for the tooltip component.
Pure refactor/bug fix.
No react hooks warnings when loaded
> fix: tooltip ID cleanup

- .husky/pre-commit
- package.json
- yarn.lock
We want to get a release out, but Husky threatens to make that release unusable by consumers using modern versions of npm (see linked issue). That is not an acceptable risk, IMO.
So, my recommendation is to remove husky for now, do a release, and replace husky with something else (as soon as possible) in preparation for code additions and future releases
Relates to (but does not close): https://github.com/trussworks/react-uswds/issues/3155
CI runs these checks
> chore(ci): Remove Husky to unblock release in preparation for replacement
