CODEOWNERS
Current structure means only John is CODEOWNER. There can be more than one if they are on the same line.
=> Correct formatting of CODEOWNERS to avoid highlanders scenario

CODEOWNERS, package.json
Added Sara and me so we can help out managing dependencies.
=> added more codeowners

CHANGELOG.md, yarn.lock
We have a lot of dependabot updates, so instead of trying to get them in one at a time this PR is the result of a `yarn upgrade`.
=> Run yarn upgrade to update our dependencies

.circleci/config.yml, CHANGELOG.md, README.md, dangerfile.ts, package.json, yarn.lock
Add [DangerJS](https://danger.systems/js/) configuration to check for contribution standards
=> Add Dangerjs

.github/workflows/auto-approve.yml, yarn.lock
Fixes #98 
Dependabot should now be able to automerge its PRs (see discussion at https://github.com/dependabot/feedback/issues/86)
=> Add auto-approve workflow for dependabot

src/components/forms/Form/Form.stories.tsx
=> Add signIn and passwordReset form templates 

package.json, yarn.lock
This PR just upgrades the uswds version to 2.7.0. I looked at the documentation and I didn't see any breaking changes. I also reviewed storybook and everything looks good!
=> chore: upgrade uswds to 2.7.0

src/stories/templates/documentation.stories.tsx, src/stories/templates/landing.stories.tsx
Fixes #88 
Adds Storybook stories for two USWDS [page templates](https://designsystem.digital.gov/page-templates)
- Landing page
- Documentation page
This demonstrates how to use our existing header, footer, grid, etc. components in a real-life page.
=> docs: add landing page and documentation page template stories

.circleci/config.yml, .gitignore, .happo.js, .storybook/config.ts, docs/contributing.md, docs/for_trussels.md, package.json, src/components/Accordion/Accordion.tsx, yarn.lock
This PR adds visual regression testing via Happo. Docs for Happo are located here: https://docs.happo.io/docs/getting-started
This PR included integrating happo with github and circleci.
=> feat: add happo

src/index.ts
Oopss. I forgot to export the card components 🤦‍♀️
=> fix(card): add card components to export

src/components/Button/Button.test.tsx
Remove accidental debug detrius
None
N/A
=> fix: remove debug detrius from button test

src/components/Footer/Footer/Footer.stories.tsx, src/components/Footer/Footer/Footer.test.tsx, src/components/Footer/Footer/Footer.tsx, src/components/Footer/FooterNav/FooterNav.stories.tsx, src/components/Footer/FooterNav/FooterNav.test.tsx, src/components/Footer/FooterNav/FooterNav.tsx, src/stories/templates/documentation.stories.tsx, src/stories/templates/landing.stories.tsx
Converts Footer and FooterNav to use size prop with enum
closes #233
=> feat(Footer,FooterNav): use size prop, deprecate boolean sizes

docs/contributing.md
The link to adding new components was not correct 😅
#248
=> docs: fix local link in contributing.md

src/components/Footer/FooterExtendedNavList/FooterExtendedNavList.tsx, src/components/header/ExtendedNav/ExtendedNav.tsx, src/components/header/MegaMenu/MegaMenu.tsx, src/components/header/Menu/Menu.tsx, src/components/header/NavList/NavList.stories.tsx, src/components/header/NavList/NavList.test.tsx, src/components/header/NavList/NavList.tsx, src/components/header/PrimaryNav/PrimaryNav.tsx
Convert from boolean props to `type` prop enum
* closes #234
Look at story and test changes
=> feat(NavList): use type prop, deprecate boolean types

src/components/forms/Fieldset/Fieldset.stories.tsx, src/components/forms/Form/Form.stories.tsx, src/components/forms/FormGroup/FormGroup.stories.tsx, src/components/forms/TextInput/TextInput.stories.tsx, src/components/forms/TextInput/TextInput.test.tsx, src/components/forms/TextInput/TextInput.tsx
use enum props, deprecate booleans
* closes #283
=> feat(TextInput): use enum props, deprecate booleans

.github/workflows/deploy-storybook.yml
Storybook deploy didn't launch correctly on new tag-  need to use correct version syntax.
closes #216
=> fix: correct version syntax in deploy-storybook.yml

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/new_component.md
Add `new_component.md` and update labels in other templates.
=> docs: Add new component issue template

src/index.ts
This is a new PR from #345 that will run the tests.  Thank you @cablej, this is a short term workaround
=> fix(NavDropDownButton): Export NavDropDownButton

CODEOWNERS, docs/for_trussels.md
Update docs, add ahobson as CODEOWNER
=> docs: add @ahobson as codeowner, remove check-in meeting

.github/dependabot.yml
Dependabot should update the example app dependencies ( based on`/example/package.json`)
closes #336 
Think I have to merge to test this...
=> ci: Dependabot should update /example dependencies 

example/package.json, example/yarn.lock
bump react-scripts to fix CVE
fixes #400 
N/A
=> build(examples): bump react-scripts to fix CVE

CHANGELOG.md, package.json
* **Search:** Add  placeholder to Search input [#403](https://github.com/trussworks/react-uswds/issues/403) ([#415](https://github.com/trussworks/react-uswds/issues/415)) ([ca31eb4](https://github.com/trussworks/react-uswds/commit/ca31eb49d76a9bea5bafc14b141ff83573bdeb05))
=> chore(release): 1.9.1

.circleci/config.yml
closes #450 
We have to merge to see that this works for dependabot
=> fix: Change happo command to check for github user

CHANGELOG.md, package.json
* Change happo command to check for github user ([#451](https://github.com/trussworks/react-uswds/issues/451)) ([cd0add9](https://github.com/trussworks/react-uswds/commit/cd0add9bd922bafe858bda9a658b9e0983ebec38))
* **storybook:** Upgrade to 6.0.12 ([#418](https://github.com/trussworks/react-uswds/issues/418)) ([65d91cc](https://github.com/trussworks/react-uswds/commit/65d91ccd77fb102e819480412cc4fc84631b6f51))
* Improve documentation for new contributors, trussels ([#402](https://github.com/trussworks/react-uswds/issues/402)) ([0849a30](https://github.com/trussworks/react-uswds/commit/0849a3093365514741387edd66e7e948861babaa))
=> chore(release): 1.9.2

example/yarn.lock
update example app deps to fix security issue
fixes #475
=> fix: update example app deps to fix security issue

CODE_OF_CONDUCT.md, README.md, docs/contributing.md
closes #454 
[This PR may have to hold until email alias is created and/or TDR is approved]
=> docs: Add Code of Conduct

.github/dependabot.yml, example/package.json
Also move example deps to devDependencies where appropriate
#538 
Merge and then check to see if dependabot does the right thing
=> build(deps-dev): Allow dependabot to update all example deps

CHANGELOG.md, package.json
*  Happo automation should skip dependabot PRs ([#453](https://github.com/trussworks/react-uswds/issues/453)) ([dc5bffc](https://github.com/trussworks/react-uswds/commit/dc5bffc88784eef283a075045172e6228cf5384f))
* Require Typescript 3.8+ ([#521](https://github.com/trussworks/react-uswds/issues/521)) ([53efe5d](https://github.com/trussworks/react-uswds/commit/53efe5d164d8dd488c94eb8bdce1c13243d04dae))
* update example app deps to fix security issue ([#476](https://github.com/trussworks/react-uswds/issues/476)) ([00fd70a](https://github.com/trussworks/react-uswds/commit/00fd70a5b597af29d54a6d5b4ca90a619ef05c51))
* Add Code of Conduct ([#455](https://github.com/trussworks/react-uswds/issues/455)) ([6b8f96c](https://github.com/trussworks/react-uswds/commit/6b8f96cae8d677d9f7a58b82db27a721b728 …
=> chore(release): 1.9.3

CHANGELOG.md, package.json
* ComboBox component ([#694](https://github.com/trussworks/react-uswds/issues/694)) ([824028a](https://github.com/trussworks/react-uswds/commit/824028a48d4f7cb2c16472893437128d8411f67b))
* Use Node 14x ([#729](https://github.com/trussworks/react-uswds/pull/729)) ([db7dc29](https://github.com/trussworks/react-uswds/commit/db7dc29395f41f19f4fba2ab425455492b9bf25d))
* Add className handling to header and footer subcomponents ([#735](https://github.com/trussworks/react-uswds/issues/735)) ([808b290](https://github.com/trussworks/react-uswds/commit/808b29036583095285560c5194b3842db45dded7))
=> chore(release): 1.10.0

CODEOWNERS, README.md, package.json
PR following the [onboarding](https://github.com/trussworks/react-uswds/blob/main/docs/for_trussels.md#onboarding) instructions since I'll be on reserve and focusing on this for a little while.
=> docs: Onboard Brandon to react-uswds

CHANGELOG.md, package.json
- **ComboBox**: Add ActionType.BLUR to indicate a user has left the field ([#902](https://github.com/trussworks/react-uswds/issues/902)) ([58159d7](https://github.com/trussworks/react-uswds/commit/58159d7430016bb88ab2fba33ab1984e0aebed66))
=> chore(release): 1.12.2

CHANGELOG.md, package.json
* File Input component ([#900](https://github.com/trussworks/react-uswds/issues/900)) ([e1ccbcd](https://github.com/trussworks/react-uswds/commit/e1ccbcd0b0c0cc3ec80cd8f0fa38afd09b29ecfa))
* Add All-Contributors section to README ([#954](https://github.com/trussworks/react-uswds/issues/954)) ([fe23df1](https://github.com/trussworks/react-uswds/commit/fe23df1acb2de244ac45ee5f1f797a1229203822))
=> chore(release): 1.13.0

CHANGELOG.md, package.json
* ComboBox "keyboard trap" and misc bugs ([#1010](https://github.com/trussworks/react-uswds/issues/1010)) ([50aef22](https://github.com/trussworks/react-uswds/commit/50aef22b3dcccad7da165e023bb05fe921e0af98))
=> chore(release): 1.13.2

CHANGELOG.md, package.json
* DateRangePicker Component ([#983](https://github.com/trussworks/react-uswds/issues/983)) ([69d34ed](https://github.com/trussworks/react-uswds/commit/69d34ed8f78ae22e29c270d877c081fe5335325c))
* Tooltip component   ([#871](https://github.com/trussworks/react-uswds/issues/871)) ([92ea5f0](https://github.com/trussworks/react-uswds/commit/92ea5f07f7212370165423ec09ed35eec3aa7e58))
* Update documentation. Show component description and prop defaults in storybook ([#1008](https://github.com/trussworks/react-uswds/issues/1008)) ([a8d267f](https://github.com/trussworks/react-uswds/commit/a8d267f6f7db8c9d3dc1c8477fe1ee6b98f9b914))
---
See https://github.com/trussworks/react-uswds/compare/1.13.2...release-1.14.0 for all release changes
=> chore(release): 1.14.0

CHANGELOG.md, package.json
* Add i18n support to DatePicker component ([#990](https://github.com/trussworks/react-uswds/issues/990)) ([2000b9c](https://github.com/trussworks/react-uswds/commit/2000b9cd1e98ab85841d448a58b41105a17a7bb4))
* Update to USWDS 2.10.3 ([#1106](https://github.com/trussworks/react-uswds/issues/1106)) ([c9f71d7](https://github.com/trussworks/react-uswds/commit/c9f71d7d7989fb9c7ab2e264d1af26436dcb66c3))
* Implement Identifier subcomponents ([#1100](https://github.com/trussworks/react-uswds/issues/1100)) ([703a60d](https://github.com/trussworks/react-uswds/commit/703a60dadc326c822748bbf50aec735e35421c60))
* **adr:** Increase ReactUSWDS version when updating USWDS version ([#1045](https://github.com/trussworks/react-uswds/issues/1045)) ([59f6720](https://github.com/trussworks/react-uswds/commit/5 …
=> chore(release): 1.16.0

docs/releasing.md
Edit releasing notes in response to #1727. Ensure we have the proper build artifact and no errors in `yarn build` before publishing
=> chore: Update release notes for publishing

src/components/forms/Fieldset/Fieldset.test.tsx, src/components/forms/Fieldset/Fieldset.tsx
Allows Fieldset to accept IntrinsicElements
Unit test should cover exactly the use-case being solved here.
=> feat: Allow intrinsic elements to be passed to Fieldset

CHANGELOG.md, package.json
* accept prop for heading level ([#1751](https://github.com/trussworks/react-uswds/issues/1751)) ([#1865](https://github.com/trussworks/react-uswds/issues/1865)) ([464756f](https://github.com/trussworks/react-uswds/commit/464756fb1e189509bde02848cc09f992357d7e1c))
=> chore(release): 2.6.0

.storybook/main.ts, package.json, yarn.lock
This adds the a11y storybook [addon](https://storybook.js.org/addons/@storybook/addon-a11y), which adds an accessibility tab and functionality to the storybook interface.
Allows people to explore the accessibility of individual components in Storybook.
Open storybook `yarn storybook` and see the "Accessibility" tab
=> build: Add storybook a11y addon

src/components/SummaryBox/SummaryBoxContent/SummaryBoxContent.tsx, src/components/SummaryBox/SummaryBoxHeading/SummaryBoxHeading.tsx, src/index.ts
=> fix: export SummaryBoxHeading and SummaryBoxContent

package.json, src/components/Footer/Footer/Footer.stories.tsx, src/components/Footer/SocialLinks/SocialLinks.stories.tsx, src/components/Footer/SocialLinks/SocialLinks.test.tsx, src/components/Footer/SocialLinks/SocialLinks.tsx, src/components/Identifier/IdentifierLink/IdentifierLink.tsx, src/components/Search/Search.test.tsx, src/components/Search/Search.tsx, src/components/forms/ComboBox/ComboBox.test.tsx, src/components/forms/ComboBox/ComboBox.tsx, src/components/forms/DatePicker/Calendar.tsx, src/components/forms/DatePicker/DatePicker.stories.tsx, src/components/forms/DatePicker/DatePicker.tsx, src/components/forms/DatePicker/YearPicker.tsx, src/components/forms/DateRangePicker/DateRangePicker.test.tsx, src/components/forms/DateRangePicker/DateRangePicker.tsx, src/index.ts, src/stories/templates/createaccount.stories.tsx, src/stories/templates/documentation.stories.tsx, src/stories/templates/landing.stories.tsx, src/stories/templates/mutliplesignin.stories.tsx, src/stories/templates/notfound.stories.tsx, src/stories/templates/signin.stories.tsx, yarn.lock
This PR upgrades USWDS to 2.13.3, and makes minimal changes required to support that version.
* Update to small Search markup (non-breaking since markup is implemented by this lib)
* Update to Footer social button markup (these icons are implemented as children so users may need to update their implementation)
* Adds missing `aria-controls` prop to ComboBox input
* Use `aria-describedby` for DatePicker hint, and `aria-labelledby` for DatePicker label (instead of combining into a single attribute)
* 2.13.0 [release notes](https://github.com/uswds/uswds/releases/tag/v2.13.0) and [diff](https://github.com/uswds/uswds/compare/v2.12.2...v2.13.0)
* 2.13.1 [release notes](https://github.com/uswds/uswds/releases/tag/v2.13.1) and [diff](https://github.com/uswds/uswds/compare/v2.13.0...v2.13.1)
* …
=> feat: USWDS 2.13.3

src/components/Search/Search.test.tsx, src/components/Search/Search.tsx
PR to merge PR #2207 from @1Maria
closes #2206
=> fix: Add defaultValue prop to Search component

package.json, yarn.lock
* build(deps-dev): Bump sass from 1.52.0 to 1.56.1 (#2223) @dependabot
* build(deps-dev): Bump webpack-cli from 4.9.2 to 5.0.0 (#2221) @dependabot
* build(deps): Bump loader-utils from 1.4.1 to 1.4.2 (#2220) @dependabot
=> build(deps): Combined dependabot pr branchs

package.json, yarn.lock
Updates further Dependabot reported vulnerabilities
`yarn test` works locally
=> chore: upgrade more things

CHANGELOG.md, package.json
[Preview changes since release 4.2.0](https://github.com/trussworks/react-uswds/compare/4.2.0...release-4.2.1)
=> chore(release): 4.2.1

docs/styles_and_assets.md
Simply changes a quoted path
Resolves #2507
=> docs: updated path

src/components/forms/Form/Form.stories.tsx
Updates [address](http://localhost:9009/?path=/story/components-form-templates--address-form) and [name](http://localhost:9009/?path=/story/components-form-templates--name-form) storybook templates
Resolves #2519 
Open [address](http://localhost:9009/?path=/story/components-form-templates--address-form) and [name](http://localhost:9009/?path=/story/components-form-templates--name-form) and compare to [USWDS templates](https://designsystem.digital.gov/templates/form-templates/)
=> docs: Updated storybook templates

README.md
We rotated active maintainers from @gidjin to myself
=> chore: Update active maintainer

.all-contributorsrc, README.md
Several recent contributors need to be added to our all-contributors
@aybeedee @m7adeel @vinodkv2511 if you **do not** want to be in our [all-contributors section of the README](https://github.com/trussworks/react-uswds#contributors-), please tag me in a comment on this PR. Otherwise, We'll merge this sometime next week. Thanks for your recent help!
=> chore: Add recent contributors

.all-contributorsrc, README.md
=> chore: add AJ Farkas as contributor

.all-contributorsrc, README.md
Adds Lea Melendez as a contributor
=> docs: add @lea-m-truss as a contributor
